### ISSUE TITLE
Closing last tab

### ISSUE THREAD

**Issue by shakvaal** [benbasson/newtabhomepage#7] opened 2015-11-09 22:23 UTC
Closing the last tab when `browser.tabs.closeWindowWithLastTab` is `false` opens a blank tab instead of a homepage one.

Latest Porteus Linux + Firefox 38 + NewTab Homepage 0.4.3

**Comment by benbasson** [comment] 2016-01-10 23:49
Pretty sure this was fixed by New Tab Homepage 0.5.0, but I have tested with 0.5.1 and Firefox 44. Can you please re-test?

**Comment by benbasson** [comment] 2016-11-24 00:29
Going to assume this is fixed unless I hear back. I am unable to reproduce the problem.

**Closed as completed by benbasson** 2016-11-24 00:29 UTC
