### ISSUE TITLE
urlbar focus

### ISSUE THREAD

**Issue by alvajose35** [benbasson/newtabhomepage#40] opened 2020-09-02 15:10 UTC
Hi Ben. I've used the newtabhomepage extension for a really long time and its always been great and simple to use. However with the latest version of FF (I'm running 80.0.1 (64-bit)) every time I open a new tab the focus goes to the url/address bar instead of the actual web page that's being open. It is super annoying to the point that I spend a couple hours trying to find a solution but came empty handed. I was force to install  the "New Tab Override by Sören Hentzschel" since that extension has the option to set the focus on the page as opposed to the url bar. You might want to add the option/update your project to tackle this new FF behavior since it makes your extension impractical.  Anyways, thanks for everything you've done and for all your time you spend helping the FF community!! Cheers!!

**Comment by alvajose35** [comment] 2020-09-02 15:26
Upon further reading I noticed this is the exact same issue as #23 from 2017. I guess it just resurfaced... Bug 1411465 is still relevant and even the developer of New Tab Override commented 4 days ago...

**Comment by Blast-City** [comment] 2020-09-17 06:16
I've posted a similar thread on reddit and an user gave me the following answear:

_**Before Firefox 61, add-on authors could control whether the cursor went into the address bar or into the page. In Firefox 61-79, the cursor went into the page automatically and add-on authors could not offer the option. Firefox 80 restored the Firefox 60 behavior: cursor is in the address bar by default, and add-on authors can offer an option to move it into the page instead.**_

**Comment by benbasson** [comment] 2021-03-25 01:08
Duplicate of #23.

Also, that Reddit comment is wrong. There was never any control over this behaviour, and there still isn't.

**Closed as completed by benbasson** 2021-03-25 01:08 UTC
