### ISSUE TITLE
Home page isn't saved as part of the browsing history in Firefox 41.0.2 / New Tab Homepage 0.5.0 / Win7

### ISSUE THREAD

**Issue by tbryhn** [benbasson/newtabhomepage#6] opened 2015-10-19 10:41 UTC
When opening a new tab the homepage is loaded correctly, but my homepage (which is a page with my most used personal links) is not stored as browsing history, and the back button can't be used to get back to the home page. Further browsing works correctly, it is only the home page that is affected.

**Comment by benbasson** [comment] 2016-01-10 23:44
Duplicate of #3

**Closed as completed by benbasson** 2016-01-10 23:44 UTC
