### ISSUE TITLE
Cursor position on windows after the first one

### ISSUE THREAD

**Issue by vlakoff** [benbasson/newtabhomepage#4] opened 2015-10-04 18:54 UTC
I finally found out what was driving me nuts starting from 0.5.0!

Before 0.5.0:
- Open first Firefox window. Cursor is inside the home page.
- Open another Firefox window. Cursor is also inside the home page.

Since 0.5.0:
- Open first Firefox window. Cursor is inside the home page.
- Open another Firefox window. Cursor is inside the location bar. Aaaand, its content is not selected, so if you type something, it is appended instead of replacing. So instead of some search terms, you end up with some erroneous location.

Windows 7, Firefox 41.0.1

I tried the [New Tab Override](https://addons.mozilla.org/en-us/firefox/addon/new-tab-override/) add-on, it has the same issue.

Maybe it is some bug in this new Firefox API? Considering this issue and #3, maybe it would be judicious to revert to the pre-0.5.0 method for the time being?

**Comment by benbasson** [comment] 2016-01-11 00:04
New windows are actually handled completely outside of New Tab Homepage (using the standard in-built Firefox code for loading the homepage). If you've got a tab problem, then I can look into it (if it's reproducible), but you should file bugs in the new window process with Mozilla.

**Comment by vlakoff** [comment] 2016-02-04 04:29
Tested with Firefox 44.0 and add-on 0.5.2, this issue is still present.
If it's a Firefox issue, I don't even have hope in filling a bug, it's so likely to sink alone and forgotten.

I've made myself a reason and stick to 0.4.3.1 with regret.

**Comment by benbasson** [comment] 2016-12-24 00:26
Closing because this has nothing to do with this add-on... New Tab Homepage doesn't hook into or use any API or code related to Firefox window opening.

**Closed as completed by benbasson** 2016-12-24 00:26 UTC
