### ISSUE TITLE
local html home page does not appear

### ISSUE THREAD

**Issue by hfgrimm** [benbasson/newtabhomepage#25] opened 2017-11-14 17:19 UTC
I just installed the new Firefox Quantum which did not allow the old "newtab" extension I was using.
I found your newtabhomepage and installed it.  When I open a new tab, nothing is displayed.
I see you already have a bug report for this.
The address I am using for my home page is: file:///C:/www/hfgrimmfam.html
Is there a variation of that address that might work?

**Comment by mprough** [comment] 2017-11-15 12:16
Same here, following this for solution

**Comment by loneswimmer** [comment] 2017-11-15 15:01
I have the same issue - I think it might be down to changes in Firefox no longer allowing access to the local file system.  It's a realy hassle for me as I have a custom page locally.

**Comment by peihana** [comment] 2017-11-15 20:52
I have 0.6.2 in Ff 57.0 (64-bit) on two desktop PCs. With my homepages set to locally hosted files, new tabs open as blank. If I change my homepage to a remote website, it opens fine. The homepages were opening fine on Ff 56.0.2. On one PC, homepage is file:///H:/guide.htm ; on the other it is file:///C:/Users/Bob/index.htm. I see that this problem was believed fixed in 0.6.2.

**Comment by peihana** [comment] 2017-11-15 22:07
New Tab Override can't open local files either. It says Ff just no longer supports it. So it's not looking promising. I have reverted to ff 56.0.2 and 0.5.3 of this addon. Will consider making Chrome my default browser instead, as I have another addon that doesn't work in Ff 57 either, and I was already starting to use Chrome on my 3-year-old PC, because Ff 56 runs like a dog on it.

**Comment by je-425** [comment] 2017-11-16 12:11
Same here. Got updated to FF 57 (Quantum), and new tabs give a blank page. Home page is a local file (actually in my Dropbox dir, so shared between all my machines). Downgraded to 56.0.2 and was told that New Tab Override 0.6.2 is not compatible with FF 56 -- funny, it worked fine with 56.0.2 yesterday...!

Any advice on which version to roll back to, anyone?

**Comment by loneswimmer** [comment] 2017-11-16 13:35
I am not sure which version to roll back to as it hasn't worked for quite a while, and there seems to be no intention to fix it.  Each release of Firefox more and more things cease to work and this latest release, "Quantum" despite being described as "fast forever" is so slow for me that I think the time has come to ditch Firefox and find another browser.  I wish I could be more positive.

**Comment by vlakoff** [comment] 2017-11-17 09:08
+1 sufferer from this issue. I don't know if this WebExtension limitation can be overcome, but I guess it cannot be…

By the way, duplicate of #24, better centralize discussions on one of the tickets.

**Comment by asmusf** [comment] 2017-11-17 23:45
FF has no problem loading a local home page on new window, so this seems silly.

**Comment by TerryMorse** [comment] 2017-11-18 07:04
Ditto

**Comment by Fanra** [comment] 2017-11-18 17:23
I also use a local file for my home page and this addon is not working for it.  I keep checking back here every day in hopes a new version has been released that fixes this.

**Comment by Dutch-TinTin** [comment] 2017-11-23 11:26
@asmusf : "FF has no problem loading a local home page on new window, so this seems silly."
Can you tell us the way to achieve this? After setting a local file as my homepage it indeed does appear when starting FF, but is does NOT appear when using the +-tab for requesting a new tab ...

**Comment by kebechsenuef** [comment] 2017-11-23 15:55
Ditto

**Comment by Chris763454357** [comment] 2017-11-24 07:15
Yikes. This is a big problem :( 

I suppose one workaround is to install apache just to host a single file so firefox can load it... That seems like stupid overkill.

**Comment by je-425** [comment] 2017-11-24 13:04
> I suppose one workaround is to install apache just to host a single file so firefox can load it... That seems like stupid overkill.

Which is why I put my homepage on Dropbox, so I can reference it from any device without having to install Apache. I can use the web link to Dropbox instead of a file link, but then it takes forever to load and it puts it in a panel within the page instead of filling the page. I also tried Google Drive, but that just displays the page source!

**Comment by benbasson** [comment] 2017-11-27 21:23
This is the same as issue #24, please track progress there.

**Closed as completed by benbasson** 2017-11-27 21:23 UTC
Labels: wontfix
