### ISSUE TITLE
Page Back is Disabled

### ISSUE THREAD

**Issue by WackoBird** [benbasson/newtabhomepage#3] opened 2015-10-03 18:40 UTC
After my new tab homepage loads and I navigate away, I can't use the back button to return to my homepage. When the homepage was settable from within firefox, the homepage would show up in the history so that you could page back to it.

ETA: One workaround I have discovered is after clicking the new page tab, I click the home button. It reloads itself and then it will show up as the first page in the history.

**Comment by vlakoff** [comment] 2015-10-04 15:06
Confirmed here.

Fun fact:
1) Open new tab, from it navigate to some page.
2) As described above, can't go back to home page.
3) Open home page in same tab.
4) From it, navigate to another page.
5) You can go back, and… you land on the page from (1)

**Comment by benbasson** [comment] 2016-01-10 23:44
I think this is due to the Firefox API I was/am using. I've had to switch API again because Mozilla have deprecated the few-month-old one that I switched to, and that seems to resolve this problem as a by-product. 

Please can you re-rest when New Tab Homepage 0.5.1 is released (use with Firefox 44) and let me know if you're still having the problem?

**Comment by vlakoff** [comment] 2016-01-11 07:25
I installed Firefox 44.0 beta 7 then tried to install addon 0.5.1 from AMO, but I got this message:

> The add-on downloaded from this site could not be installed because it appears to be corrupt.

It seems version 0.5.1 is the only one giving this error. Maybe it's some AMO issue? I don't know.

**Comment by WackoBird** [comment] 2016-01-24 20:45
The problem disappeared after an update a while back. However, since that time I have switched to Pale Moon, so there is no longer a need for your addon. Thank you for your assistance.

**Comment by vlakoff** [comment] 2016-02-04 04:19
Tested with Firefox 44.0 (64-bit) and add-on 0.5.1/0.5.2, the issue seems to be fixed.

**Comment by benbasson** [comment] 2016-11-24 00:29
This was fixed in 0.5.1.

**Closed as completed** 2016-11-24 00:28 UTC
